apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    # https://argoproj.github.io/argo-cd/user-guide/compare-options/
    # argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(1024) ; print 'drb 5';"]
      restartPolicy: Never
  backoffLimit: 4